version: "3.9"

services:
  api_dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      DB_HOST: postgres_dev
      DB_PORT: 5432
      DB_PASS: example123
      DB_USER: postgres
      DB_DBNAME: fastapi
      JWT_SECRET_KEY: a3dca4ec84db340286a09302da4064dcf7683944aae33e4a0af15a1d4d520caf
      JWT_ALGORITHM: HS256
      JWT_TOKEN_EXPIRE_MIN: 60
    depends_on:
      - postgres_dev
    volumes:
      - ./:/usr/src/app:ro
    command: bash -c "while !</dev/tcp/postgres_dev/5432; do sleep 1; done; alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  postgres_dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example123
      POSTGRES_DB: fastapi
    volumes:
      - ./pgdata_dev:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin_dev:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: example123
      PGADMIN_DEFAULT_EMAIL: user@example.com
    ports:
      - 8080:80
