"""phone number

Revision ID: 69a304af2f62
Revises: 205d46b5ae97
Create Date: 2021-11-04 17:24:24.085969

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '69a304af2f62'
down_revision = '205d46b5ae97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
